version: '3.3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api/:/api
    working_dir: /api
    expose:
      - 9080
    ports:
      - '9080:9080'
    hostname: api
    depends_on:
      - redis
    networks:
      - redis-net

  node:
    image: node:10
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - 9090
    ports:
      - '9090:9090'
    command: npm run docker::start
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    image: redis:4.0.5-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
